name: Build/release

on:
  #push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build
        run: |
           npm install
           npx electron-forge make

      - name: Integrate ffmpeg
        shell: bash
        run: |
           curl -s -o ffmpeg.7z -L https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z
           7z x ffmpeg.7z
           mkdir -p out/enhancr-win32-x64/resources/app/src/python/ffmpeg/
           ls -l ffmpeg*
           mv ffmpeg-*-essentials_build/bin/ffmpeg.exe out/enhancr-win32-x64/resources/app/src/python/ffmpeg/

      - name: Package release (app)
        run: |
           cd out
           7z a -t7z -mx=5 ../app-only-win64.7z enhancr-win32-x64

      - name: Integrate VS portable
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        shell: bash
        run: |
           curl -s -o vs_portable.7z -L https://github.com/AmusementClub/tools/releases/download/2022H2.1b2p/vapoursynth_portable_22H2.1b2p_full.7z
           7z x vs_portable.7z
           mv vapoursynth/* out/enhancr-win32-x64/resources/app/src/python/bin/
           rm vs_portable.7z

      - name: Package release (VS)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        run: |
           cd out
           7z a -t7z -mx=5 ../vs-only-win64.7z enhancr-win32-x64/resources/app/src/python/bin/

      - name: Package everything
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        shell: bash
        run: |
           cd out
           7z a -t7z -mx=5 -v1500M ../app-full-win64.7z enhancr-win32-x64
           cd ..
           ls -l app-full-win64.7z*

      - name: Upload
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: logs
          path: C:\npm\cache\_logs
          retention-days: 1

      - name: Release (Part 1)
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        with:
          tag_name: ${{ inputs.tag }}
          files: |
            app-only-win64.7z
            vs-only-win64.7z
          fail_on_unmatched_files: true
          generate_release_notes: false
          prerelease: true

      - name: Release (Part 2)
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        with:
          tag_name: ${{ inputs.tag }}
          files: |
            app-full-win64.7z*
          fail_on_unmatched_files: true
          generate_release_notes: false
          prerelease: true
